#%RAML 1.0 DataType
type: object
properties:
  EmployeId?:
    type: integer
  FirstName?:
    type: string
  LastName: string
  Birthdate?: 
    type: datetime-only
    example: "2021-02-28T04:18:59"   
  Address?: string
  Salary?: number
  Age?: integer
  Phone?: string
  Email?: string
  Status?:  string